### PR TITLE
document library-usage in README

### PR DESCRIPTION
**Pull request by andrewdea**
Brief documentation of the the three library functions:
 - `complexipy.main.main`
 - `complexipy.main.file_complexity`
 - `complexipy.main.code_complexity`
 
Happy to add more details if needed.

Related issue: https://github.com/rohaquinlop/complexipy/issues/48

### CODE REVIEW

**Review by rohaquinlop — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by andrewdea** [comment]
thank you @rohaquinlop! 
Do we need any more steps to release this new version of the code?

**Comment by rohaquinlop** [comment]
@andrewdea I was thinking to make a few changes before the release

**Comment by andrewdea** [comment]
@rohaquinlop understood :)
I'd love to be able to pip install this latest version for some projects I'm working on, so I'm happy to help speed this up if possible.
I know it could be installed directly from git instead of from PyPI, but that adds an extra layer of complexity (no pun intended 😄), which I'd like to avoid

**Pull request merged**
